### ISSUE TITLE
v2.0 Umbrella Issue

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#828]
- [ ] Hooks (#1063)
- [ ] Use JSX generics on `<Field<Values>>` (#726 , #370)
- [ ] Add debugger / logger
- [ ] Begin deprecating `dirty`, with warning (replaced with`isDirty`) (#353)
- [ ] Add `submitAttemptCount`, `submitFailureCount`, `submitSuccessCount` and computed boolean counters? `didSubmitSucceed` and `didSubmitFail` or `submitFailure` / `submitSuccess`
- [ ] Add `warnings`, `setFieldWarning`, `setWarnings` (#1001, #389)
- [x] Async `onSubmit` (#486 , #500)
- [x] Ensure that Formik context value is immutable
- [ ] Promisify or give callbacks to all `setFieldXXX` functions

**Comment by prichodko** [comment]
I was just recently thinking about submitting RFC proposing to have every necessary `set***` method (which is using setState under the hood) promisified the same way as `setState` in [unstated](https://github.com/jamiebuilds/unstated).

**Comment by prichodko** [comment]
I rememberer people asking for a way how to handle API errors, is that something which is gonna be addressed by `submitError` ?

**Comment by jaredpalmer** [comment]
Yes that's the idea.

**Comment by prichodko** [comment]
We could finally land - https://github.com/jaredpalmer/formik/pull/579

**Comment by cdock1029** [comment]
Any thoughts about having a `stateReducer` type of prop... to intercept changes, conditional updates, dynamic field rendering etc? Allows for custom handling of state without controlling it.

Had an idea here but closed it.. https://github.com/jaredpalmer/formik/pull/763

Idea was from downshift having same functionality.

**Comment by prichodko** [comment]
@cdock1029 no, you can read more here - https://github.com/jaredpalmer/formik/issues/401

**Comment by klis87** [comment]
> Yeah i actually have some thoughts about breaking the way that <Field component > and <Field render> work.
I think <Field component={}> should inject onChange, onBlur, and value as flat props (instead of collecting/namespacing them into { field, form} like it currently does)

@jaredpalmer  I am worried about this a little. I often use Field to get form  data from context, and often I need to have more state that just 1 field, for example to compare it with another field etc. I like the idea to giving value specific to needed field for convenience, but I often need the whole form state as well there, so I can derive from state in any way flexibly.

**Comment by jaredpalmer** [comment]
@klis87 When the next version of React comes out, you'll be able to call 

```js
const { // anything } = FormikContext.read();
```

**Comment by klis87** [comment]
@jaredpalmer ok that would be great, but how I could get a reference to `FormikContext` from a Field component?

**Comment by jaredpalmer** [comment]
In the next version of react you can just read from context in any render phase method.

```
import { FormikContext } from 'formik';

const MyExtraThing = () => {
   const { /* anything */ } = FormikContext.read();
   return null
}
```

**Comment by klis87** [comment]
@jaredpalmer will it work with multiple Formik instances at the same time, picking the right context from closest Formik parent depending on a component tree? If yes, then I wont be worried anymore :)

**Comment by klis87** [comment]
@jaredpalmer Thanks, that sounds awesome.

**Comment by Rockson** [comment]
@jaredpalmer Also why not <Formik<Values> [...]> ?
Actually there was a discussion about this in (ts repo)[https://github.com/Microsoft/TypeScript/issues/19728]

It would be really handy to have something like:

```
class MyFormik extends FormikWrapper<MyValues> {}

<MyFormik.Formik>
  <MyFormik.Field />
</MyFormik.Formik>
```

But this is not yet possible and typescript will not add generics to namespaces. However this can be done with a wrapping generic Class as suggested in the issue.

**Comment by prichodko** [comment]
@jaredpalmer let's remove deprecated `setError` in 2.0.

**Comment by prichodko** [comment]
After reading @mjackson's next steps for React Router - https://github.com/ReactTraining/react-router/issues/6362, I think it would be great if Formik also took part in unifying `render`/`children` prop. It will be definitely controversial at the beginning, but I agree that less API is better.

**Comment by prichodko** [comment]
Migrate `withFormik` and `Field`s to use new `forwardRef`, this is breaking change.

**Comment by prichodko** [comment]
We should also make sure it will run smoothly with the new version of React, @jaredpalmer have you tried to run Formik in [Strict Mode](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects)?

**Comment by smeijer** [comment]
I have great understanding for busy life's and lack of time to maintain open source projects. (see my own projects). 

I do however also have developed some hate against stale[bot]. Issues without activity are not resolved, and should thereby not be automatically closed.

I see inactivity as a form of respect to the author. An understanding that `+1` doesn't help. An understanding that the author has a personal life too.

The issue is open, so the author is aware. It will be closed when it's fixed. Not sooner, not later.

**Comment by crosscompile** [comment]
Maybe we can add labels to stale bot's

**Comment by jaredpalmer** [comment]
This is obviously a mistake as v2 is being actively developed #1063

**Comment by lourenci** [comment]
Is `dirty` going to be by field like `touched`?

**Comment by johnrom** [comment]
I'm really looking forward to seeing `<Field<TValue> name={keyof typeof TValue} />` implemented, as this is a part that needs utmost type safety when working with many forms. I'd be willing to spend some working on it if you need help. Is there an issue tracked specifically for this?

My recommendation having implemented something similar is to return an alias to Field from the render function of Formik, allowing users to opt-in to this type safety instead of breaking back-compat. Once you've figured out how you want to _really_ type the Field, you can change FieldAlias from `React.ComponentClass<FieldAttributes<Values>>` to `Field<Values>`.

```
// Formik.tsx
import { Field } from './Field';

export class Formik<Values = FormikValues> extends React.Component<
  FormikConfig<Values>,
  FormikState<Values>
> {
  FieldAlias: new () => React.ComponentClass<FieldAttributes<Values>> = Field;

  getFormikBag = () => {
    return {
      // ...
      Field: this.Field,
    }
  }
}
```

**Comment by FredyC** [comment]
@gespispace (and others) ... it seems that https://github.com/jaredpalmer/formik/pull/1063 is the most active thread in regards to V2. Looking at the checklist above, all other linked issues are either closed or stale.

**Comment by jdetle** [comment]
Hey, just checked out the 2.0 alpha and the deprecation warnings are overflowing my console and bogging everything down even though I refactored all of my fields to used the correct child function api over using render props. Thought you should know if you haven't seen this already @jaredpalmer.

**Comment by jaredpalmer** [comment]
@jdetle are the warnings wrong? or just overwhelming?

**Comment by jaredpalmer** [comment]
@jdetle Thanks for the feedback. I just published a new alpha that will only warn one time when the component mounts

**Comment by jdetle** [comment]
Another question/issue: in 1.0 I have a field:
```ts
<FieldArray name="themeItems">
{(arrayHelpers) => ...
 <Field 
    name={`themeItems.${index}.value`}
    render={({ field, form }: FieldProps<IThemeItems>) => ...
/>
}
<FieldArray>
```

`field.value` has type IThemeItems, which didn't seem to be the resolved type in 1.0, and definitely is in 2.0. What is the appropriate type parameter to pass to FieldProps in this case of a fieldArray Field element?

**Comment by jdetle** [comment]
Still getting warnings when there are no instances of this happening in my codebase: 
![Screen Shot 2019-04-11 at 12 56 07 PM](https://user-images.githubusercontent.com/10944582/55980319-d06a8f80-5c59-11e9-9ecc-82152f5c6197.png)

This is a picture of my tests. I'm happy to help address this in a PR if you can point me in the right way. Loving all that formik is doing for us.

**Comment by FredyC** [comment]
I am at the crossroads of picking up a form library for refactoring our production apps. They are using now abandoned `react-form`. It has been replaced by `informed` which tries to be somewhat backward compatible so it should be an obvious choice.

I must say I am kind torn apart here. Formik looks really nice, but I don't want to rewrite to V1 and then again to V2. Unfortunately, for someone who hasn't used Formik yet, the lack of documentation is somewhat scary.

Would love to hear some advice here, most importantly what are major differences with V1 and if you would recommend V2 for production already or it's still too much in the wind?

**Comment by nareshbhatia** [comment]
Running into the same issue. I am getting the following warning, but can't find any docs or examples on 
`<Formik as>`

> Warning: `<Field component>` has been deprecated and will be removed in future versions of Formik. Use `<Formik as>` instead. Note that with the `as` prop, all props are passed directly through and not grouped in `field` object key.

All I need is one working example!

**Comment by jdetle** [comment]
Personally I'm cool with the errors and lack of docs because its in alpha, just want to help the dev process.

**Comment by jaredpalmer** [comment]
The docs are in the branch. I updated them for Field as IIRC.

**Comment by nareshbhatia** [comment]
@jaredpalmer, thanks for pointing me in the right direction. The warning message threw me off - it says `<Formik as>` but I think it should say `<Field as>` (which is described [here](https://github.com/jaredpalmer/formik/blob/hooks/docs/api/field.md)).

**Comment by jaredpalmer** [comment]
Probably a mistake. Can you send a PR?

**Comment by nareshbhatia** [comment]
Sent: https://github.com/jaredpalmer/formik/pull/1434

**Comment by PetroPavlenko** [comment]
Looks like initialValues is now required in Formik. It's the only 1 error that I had while migrating to v2 🎉
@jaredpalmer Should we made initialValues as an empty object by default?

**Comment by Andreyco** [comment]
I'd like to nominate improved `FieldMetaProps` improvement allowing us to specify `error` type

```ts
export interface FieldMetaProps<Value, Error = string> {
  value: Value;
  error?: Error;
  touched: boolean;
  initialValue?: Value;
}
```

**Comment by jaredpalmer** [comment]
Yeah as long it defaults to string

**Comment by atultherajput** [comment]
I am using formik 1.5.4 but still I am not able to use field component. 
This is working: `<Field type="email" name="email" placeholder="Email" />` But this is not working:
`<Field component="select" name="color">
                                        <option value="red">Red</option>
                                        <option value="green">Green</option>
                                        <option value="blue">Blue</option>
                                    </Field>`

**Comment by johnrom** [comment]
As part of #1533, I'm locking this issue. I'll leave it open so that the milestone is discoverable from here, and because the Pinned status is helpful. Problems or questions resulting from the v2 branch should result in new issues (please search for existing issues first!). Anything determined actionable for the release of v2.0 will be added to the [v2.0 milestone](https://github.com/jaredpalmer/formik/milestone/3). @andreyco can you create an issue for your `FieldMetaProps` request?
